"use strict";

const icons={arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',home:'<path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1v-9Z"/>',check:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="m8 14 2.5 2.5L16 11"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5v13Z"/><path d="M4 19.5A2.5 2.5 0 0 0 6.5 22H20v-5"/>',wallet:'<path d="M4 5h15a2 2 0 0 1 2 2v12H4a2 2 0 0 1-2-2V5.5A2.5 2.5 0 0 1 4.5 3H18"/><path d="M15 11h6v5h-6a2.5 2.5 0 0 1 0-5Z"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',notice:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>',logout:'<path d="m10 17 5-5-5-5m5 5H3m12-9h5a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-5"/>',eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',"eye-off":'<path d="m3 3 18 18M10.6 5.2A11.4 11.4 0 0 1 12 5c6.5 0 10 7 10 7a16 16 0 0 1-2.1 3.2M6.6 6.6C3.6 8.6 2 12 2 12s3.5 7 10 7a10.7 10.7 0 0 0 4.1-.8M9.9 9.9a3 3 0 0 0 4.2 4.2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/>',receipt:'<path d="M6 2h12v20l-3-2-3 2-3-2-3 2V2Z"/><path d="M9 7h6m-6 4h6m-6 4h4"/>',spark:'<path d="m12 3 1.4 4.1 4.1 1.4-4.1 1.4L12 14l-1.4-4.1-4.1-1.4 4.1-1.4L12 3Z"/>'};
const state={token:localStorage.getItem("lakshya_parent_token"),data:null,view:"overview"};
const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.spark}</svg>`;
const esc=(value="")=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const initials=name=>String(name||"ST").split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();
const money=value=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value||0));
const dateText=value=>value?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short"}).format(new Date(value)):"Date pending";
const dateLong=value=>value?new Intl.DateTimeFormat("en-IN",{weekday:"short",day:"numeric",month:"short"}).format(new Date(value)):"Date pending";
const timeText=value=>new Intl.DateTimeFormat("en-IN",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const reducedMotion=()=>matchMedia("(prefers-reduced-motion: reduce)").matches;

function injectIcons(root=document){$$('[data-icon]',root).forEach(node=>{node.innerHTML=icon(node.dataset.icon);});}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});let body={};try{body=await response.json();}catch{}if(response.status===401){clearSession();showLogin("Your session expired. Sign in again.");}if(!response.ok){const detail=body?.detail;throw new Error(typeof detail==="string"?detail:detail?.message||body?.error?.message||"Unable to complete this request.");}return body;}
function clearSession(){state.token=null;state.data=null;localStorage.removeItem("lakshya_parent_token");}
function showLogin(message=""){$("#parent-shell").classList.add("hidden");$("#login-screen").classList.remove("hidden");$("#login-password").value="";if(message){$("#login-error").textContent=message;$("#login-error").classList.remove("hidden");}else{$("#login-error").classList.add("hidden");}requestAnimationFrame(()=>$("#login-email").focus());}
function toast(message){const node=document.createElement("div");node.className="toast";node.textContent=message;$("#toast-region").append(node);setTimeout(()=>node.remove(),3200);}
function empty(name,title,copy=""){return `<div class="empty"><div><span>${icon(name)}</span><strong>${esc(title)}</strong>${copy?`<p>${esc(copy)}</p>`:""}</div></div>`;}

async function initialize(){injectIcons();bindEvents();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});if(!state.token){showLogin();return;}try{await loadPortal();}catch(error){clearSession();showLogin(error.message);}}
async function login(event){event.preventDefault();const form=event.currentTarget,button=$("#login-button"),label=$("#login-button-label");if(!form.reportValidity())return;button.disabled=true;label.textContent="Signing in…";$("#login-error").classList.add("hidden");try{const data=new FormData(form);const result=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:String(data.get("email")).trim(),password:String(data.get("password"))})});state.token=result.access_token;localStorage.setItem("lakshya_parent_token",state.token);await loadPortal();}catch(error){clearSession();showLogin(error.message);}finally{button.disabled=false;label.textContent="Sign in";}}
async function loadPortal(){state.data=await api("/api/portal/bootstrap");$("#login-screen").classList.add("hidden");$("#parent-shell").classList.remove("hidden");renderAll();showView("overview");}
async function logout(){const token=state.token;if(token){try{await fetch("/api/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}});}catch{}}clearSession();showLogin();toast("Signed out securely.");}

function showView(view){if(!$("#"+view))return;state.view=view;$$('.app-view').forEach(node=>node.classList.toggle("active",node.id===view));$$('[data-view]').forEach(node=>{const active=node.dataset.view===view;node.classList.toggle("active",active);active?node.setAttribute("aria-current","page"):node.removeAttribute("aria-current");});const titles={overview:"Overview",attendance:"Attendance",academics:"Academics",fees:"Fees",more:"More"};$("#header-title").textContent=titles[view];$("#parent-main").focus({preventScroll:true});window.scrollTo({top:0,behavior:reducedMotion()?"auto":"smooth"});}
function renderAll(){const {profile,assignments}=state.data,name=profile.guardian||"Parent";$("#guardian-greeting").textContent=`Welcome, ${name.split(/\s+/)[0]}`;$("#child-name").textContent=profile.fullName;$("#child-program").textContent=[profile.program,profile.batch].filter(Boolean).join(" · ")||"Program pending";$("#child-avatar").textContent=initials(profile.fullName);$("#header-avatar").textContent=initials(name);$("#work-badge").textContent=assignments.length;$("#work-badge").classList.toggle("hidden",!assignments.length);renderOverview();renderAttendance();renderAcademics();renderFees();renderMore();injectIcons();}
function metric(label,value,attention=false){return `<article class="metric-card ${attention?"attention":""}"><span>${esc(label)}</span><strong>${esc(value)}</strong></article>`;}
function renderOverview(){const {summary,schedule,assignments,notices}=state.data;$("#overview-metrics").innerHTML=[metric("Attendance",summary.attendanceRate==null?"—":`${summary.attendanceRate}%`),metric("Pending work",String(summary.openAssignments),summary.openAssignments>0),metric("Upcoming classes",String(summary.upcomingClasses)),metric("Fees due",money(summary.outstandingAmount),summary.outstandingAmount>0)].join("");const next=schedule.find(item=>new Date(item.startsAt)>=new Date());$("#next-class").innerHTML=next?`<article class="class-card"><div class="class-time">${timeText(next.startsAt)}</div><div><strong>${esc(next.subject)}</strong><small>${dateLong(next.startsAt)}</small><div class="class-meta"><span class="tag">${esc(next.faculty)}</span><span class="tag">${esc(next.room)}</span></div></div></article>`:empty("calendar","No upcoming class","The next published class will appear here.");$("#pending-work").innerHTML=assignments.slice(0,3).map(item=>`<div class="compact-row"><span class="row-icon">${icon("book")}</span><span><strong>${esc(item.title)}</strong><small>${esc(item.subject)}</small></span><time>${dateText(item.dueAt)}</time></div>`).join("")||empty("check","Nothing pending","Published assignments will appear here.");const notice=notices[0];$("#latest-notice").innerHTML=notice?noticeCard(notice):empty("notice","No institute updates");}
function renderAttendance(){const rows=state.data.attendance,rate=state.data.summary.attendanceRate,present=rows.filter(item=>["present","late","excused"].includes(item.status)).length;$("#attendance-summary").innerHTML=`<div class="attendance-ring" style="--attendance:${rate||0}%"><div><strong>${rate==null?"—":`${rate}%`}</strong><small>Overall</small></div></div><div class="attendance-copy"><strong>${rows.length?`${present} of ${rows.length} classes attended`:"No attendance yet"}</strong><p>${rows.length?"Attendance includes present, late and excused records.":"Records will appear after submitted class attendance."}</p></div>`;$("#attendance-list").innerHTML=rows.length?rows.map(item=>`<article class="attendance-row"><time>${dateText(item.startsAt)}</time><span><strong>${esc(item.subject)}</strong><small>${timeText(item.startsAt)}${item.reason?` · ${esc(item.reason)}`:""}</small></span><em class="status status-${esc(item.status)}">${esc(item.status)}</em></article>`).join(""):empty("check","Attendance not recorded yet");}
function renderAcademics(){const {schedule,assignments}=state.data;$("#schedule-list").innerHTML=schedule.length?schedule.map(item=>`<article class="timeline-card"><div class="timeline-time">${dateText(item.startsAt)}<br>${timeText(item.startsAt)}</div><div><h3>${esc(item.subject)}</h3><p>${esc(item.faculty)}</p><footer><span class="tag">${esc(item.room)}</span><span class="tag">${esc(item.subjectCode)}</span></footer></div></article>`).join(""):empty("calendar","Schedule not published");$("#assignment-list").innerHTML=assignments.length?assignments.map(item=>`<article class="assignment-card"><header><span class="subject-mark">${esc(item.subject.slice(0,3).toUpperCase())}</span><span class="due-pill">Due ${dateText(item.dueAt)}</span></header><h3>${esc(item.title)}</h3><p>${esc(item.instructions||"Open the published material for details.")}</p><footer><span>${esc(item.subject)} · ${esc(item.status||"Published")}</span><a class="assignment-action" href="${esc(item.externalUrl)}" target="_blank" rel="noopener">Open</a></footer></article>`).join(""):empty("book","No assignments published");}
function renderFees(){const fees=state.data.fees,percent=fees.agreedAmount?Math.min(100,Math.round(fees.paidAmount/fees.agreedAmount*100)):0;$("#fee-hero").innerHTML=`<div class="fee-top"><span><span>Outstanding</span><strong>${money(fees.outstandingAmount)}</strong></span><span class="fee-state">${fees.outstandingAmount?"Payment due":"Up to date"}</span></div><div class="fee-progress"><span style="width:${percent}%"></span></div><div class="fee-total"><span>Paid<strong>${money(fees.paidAmount)}</strong></span><span>Agreed fee<strong>${money(fees.agreedAmount)}</strong></span><span>Progress<strong>${percent}%</strong></span></div>`;$("#payment-list").innerHTML=fees.payments.length?fees.payments.map(item=>`<article class="payment-row"><span class="payment-icon">${icon("receipt")}</span><span><strong>${dateText(item.date)}</strong><small>${esc(item.method||"Method not recorded")} · ${esc(item.status)}</small></span><strong>${money(item.amount)}</strong></article>`).join(""):empty("receipt","No payments recorded");}
function noticeCard(item){return `<article class="notice-card"><h3>${esc(item.title)}</h3><p>${esc(item.body)}</p><time>${dateLong(item.publishedAt)}</time></article>`;}
function renderMore(){const {profile,notices}=state.data;$("#profile-card").innerHTML=`<span class="profile-avatar">${initials(profile.fullName)}</span><span><strong>${esc(profile.fullName)}</strong><span>${esc(profile.admissionNumber)} · ${esc(profile.program||"Program pending")}</span><span>${esc(profile.batch||"Batch pending")}</span></span>`;$("#notice-list").innerHTML=notices.length?notices.map(noticeCard).join(""):empty("notice","No notices published");}
function togglePassword(){const field=$("#login-password"),button=$("#password-toggle"),glyph=$("[data-icon]",button),show=field.type==="password";field.type=show?"text":"password";button.setAttribute("aria-label",show?"Hide password":"Show password");glyph.dataset.icon=show?"eye-off":"eye";injectIcons(button);}
function bindEvents(){$("#login-form").addEventListener("submit",login);$("#password-toggle").addEventListener("click",togglePassword);$("#signout-button").addEventListener("click",logout);$("#profile-button").addEventListener("click",()=>showView("more"));document.addEventListener("click",event=>{const view=event.target.closest("[data-view]")?.dataset.view||event.target.closest("[data-go]")?.dataset.go;if(view)showView(view);});}
initialize();
