"use strict";

const icons={arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',home:'<path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1v-9Z"/>',check:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="m8 14 2.5 2.5L16 11"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5v13Z"/><path d="M4 19.5A2.5 2.5 0 0 0 6.5 22H20v-5"/>',exam:'<path d="M7 3h10a2 2 0 0 1 2 2v16H5V5a2 2 0 0 1 2-2Z"/><path d="M9 7h6M9 11h6m-6 4h3"/><path d="m14 16 1.5 1.5L19 14"/>',wallet:'<path d="M4 5h15a2 2 0 0 1 2 2v12H4a2 2 0 0 1-2-2V5.5A2.5 2.5 0 0 1 4.5 3H18"/><path d="M15 11h6v5h-6a2.5 2.5 0 0 1 0-5Z"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',notice:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>',logout:'<path d="m10 17 5-5-5-5m5 5H3m12-9h5a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-5"/>',eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',"eye-off":'<path d="m3 3 18 18M10.6 5.2A11.4 11.4 0 0 1 12 5c6.5 0 10 7 10 7a16 16 0 0 1-2.1 3.2M6.6 6.6C3.6 8.6 2 12 2 12s3.5 7 10 7a10.7 10.7 0 0 0 4.1-.8M9.9 9.9a3 3 0 0 0 4.2 4.2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/>',receipt:'<path d="M6 2h12v20l-3-2-3 2-3-2-3 2V2Z"/><path d="M9 7h6m-6 4h6m-6 4h4"/>',spark:'<path d="m12 3 1.4 4.1 4.1 1.4-4.1 1.4L12 14l-1.4-4.1-4.1-1.4 4.1-1.4L12 3Z"/>'};
const views=new Set(["overview","attendance","academics","fees","messages","more"]);
const hashView=()=>views.has(location.hash.slice(1))?location.hash.slice(1):"overview";
const state={token:localStorage.getItem("lakshya_parent_token"),identity:(()=>{try{return JSON.parse(localStorage.getItem("lakshya_parent_user")||"null");}catch{return null;}})(),data:null,communication:null,view:hashView(),online:navigator.onLine};
const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.spark}</svg>`;
const esc=(value="")=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const initials=name=>String(name||"ST").split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();
const money=value=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value||0));
const asInstant=value=>{if(value instanceof Date)return value;const text=String(value||"");return new Date(/[zZ]$|[+-]\d{2}:?\d{2}$/.test(text)||/^\d{4}-\d{2}-\d{2}$/.test(text)?text:`${text}Z`);};
const dateText=value=>value?new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short"}).format(asInstant(value)):"Date pending";
const dateLong=value=>value?new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",weekday:"short",day:"numeric",month:"short"}).format(asInstant(value)):"Date pending";
const timeText=value=>new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit"}).format(asInstant(value));
const reducedMotion=()=>matchMedia("(prefers-reduced-motion: reduce)").matches;

function injectIcons(root=document){$$('[data-icon]',root).forEach(node=>{node.innerHTML=icon(node.dataset.icon);});}
function setConnectionState(online){const changed=state.online!==online;state.online=online;document.documentElement.classList.toggle("is-offline",!online);let banner=$("#connection-banner");if(!banner){banner=document.createElement("div");banner.id="connection-banner";banner.className="connection-banner";banner.setAttribute("role","status");banner.setAttribute("aria-live","polite");document.body.append(banner);}banner.textContent=online?"Connection restored.":"You are offline. Saved sign-in remains available.";banner.classList.toggle("visible",!online||changed);if(online&&changed)setTimeout(()=>banner.classList.remove("visible"),2200);}
async function resilientFetch(path,options={}){const attempts=String(options.method||"GET").toUpperCase()==="GET"?2:1;let lastError;for(let attempt=0;attempt<attempts;attempt+=1){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(path,{cache:"no-store",...options,signal:controller.signal});clearTimeout(timer);setConnectionState(true);if(response.status>=500&&attempt+1<attempts)continue;return response;}catch(error){clearTimeout(timer);lastError=error;setConnectionState(navigator.onLine);if(attempt+1<attempts)continue;}}const error=new Error(lastError?.name==="AbortError"?"The server took too long to respond. Try again.":"Unable to reach the server. Check your connection and retry.");error.status=0;error.transient=true;throw error;}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await resilientFetch(path,{...options,headers});let body={};try{body=await response.json();}catch{}if(response.status===401){clearSession();showLogin("Your session expired. Sign in again.");}if(!response.ok){const detail=body?.detail,error=new Error(typeof detail==="string"?detail:detail?.message||body?.error?.message||(response.status>=500?"The service is temporarily unavailable. Try again.":"Unable to complete this request."));error.status=response.status;error.transient=response.status>=500;throw error;}return body;}
function clearSession(){state.token=null;state.identity=null;state.data=null;state.communication=null;localStorage.removeItem("lakshya_parent_token");localStorage.removeItem("lakshya_parent_user");}
function showLogin(message=""){$("#boot-screen").classList.add("hidden");$("#password-change-screen").classList.add("hidden");$("#parent-shell").classList.add("hidden");$("#login-screen").classList.remove("hidden");$("#login-password").value="";if(message){$("#login-error").textContent=message;$("#login-error").classList.remove("hidden");}else{$("#login-error").classList.add("hidden");}requestAnimationFrame(()=>$("#login-mobile").focus());}
function showPasswordChange(identity){state.identity=identity;$("#boot-screen").classList.add("hidden");$("#login-screen").classList.add("hidden");$("#parent-shell").classList.add("hidden");$("#password-change-screen").classList.remove("hidden");$("#password-change-form").reset();$("#password-change-error").classList.add("hidden");requestAnimationFrame(()=>$("[name=currentPassword]",$("#password-change-form")).focus());}
function showStartupError(error){$("#login-screen").classList.add("hidden");$("#password-change-screen").classList.add("hidden");$("#parent-shell").classList.add("hidden");const boot=$("#boot-screen");boot.classList.remove("hidden");let panel=$("#startup-error");if(!panel){panel=document.createElement("div");panel.id="startup-error";panel.className="startup-error";panel.innerHTML="<strong>Parent portal is temporarily unavailable</strong><p></p><button type=\"button\">Retry</button>";boot.append(panel);$("button",panel).addEventListener("click",()=>location.reload());}$("p",panel).textContent=error.message;}
function toast(message){const node=document.createElement("div");node.className="toast";node.textContent=message;$("#toast-region").append(node);setTimeout(()=>node.remove(),3200);}
function empty(name,title,copy=""){return `<div class="empty"><div><span>${icon(name)}</span><strong>${esc(title)}</strong>${copy?`<p>${esc(copy)}</p>`:""}</div></div>`;}

async function initialize(){injectIcons();bindEvents();setConnectionState(navigator.onLine);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});if(!state.token){showLogin();return;}try{const identity=state.identity||await api("/api/auth/me");if(identity.role!=="parent"){const error=new Error("This login is not assigned to the Parent portal.");error.status=403;throw error;}state.identity=identity;localStorage.setItem("lakshya_parent_user",JSON.stringify(identity));if(identity.mustChangePassword){showPasswordChange(identity);return;}await loadPortal();}catch(error){if(error.status===403){clearSession();showLogin(error.message);}else if(error.status!==401)showStartupError(error);}}
async function login(event){event.preventDefault();const form=event.currentTarget,button=$("#login-button"),label=$("#login-button-label");if(!form.reportValidity())return;button.disabled=true;label.textContent="Signing in…";$("#login-error").classList.add("hidden");try{const data=new FormData(form);const result=await api("/api/auth/login",{method:"POST",body:JSON.stringify({mobile:String(data.get("mobile")).trim(),password:String(data.get("password"))})});state.token=result.access_token;const account=result.user;if(account.role!=="parent")throw new Error("This login is not assigned to the Parent portal.");state.identity=account;localStorage.setItem("lakshya_parent_token",state.token);localStorage.setItem("lakshya_parent_user",JSON.stringify(account));if(account.mustChangePassword){showPasswordChange(account);return;}await loadPortal();}catch(error){if(state.token&&error.status!==401&&(error.transient||error.status===0))showStartupError(error);else{clearSession();showLogin(error.message);}}finally{button.disabled=false;label.textContent="Sign in";}}
async function changePassword(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const data=new FormData(form),currentPassword=String(data.get("currentPassword")),newPassword=String(data.get("newPassword")),error=$("#password-change-error");if(newPassword!==String(data.get("confirmPassword"))){error.textContent="The new passwords do not match.";error.classList.remove("hidden");return;}if(newPassword===currentPassword){error.textContent="Choose a personal password different from the temporary password.";error.classList.remove("hidden");return;}const button=$("#password-change-button"),idle=button.innerHTML;button.disabled=true;button.textContent="Saving…";error.classList.add("hidden");try{const mobile=state.identity?.mobile||"";await api("/api/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword,newPassword})});clearSession();showLogin("Personal password saved. Sign in again.");$("#login-mobile").value=mobile;}catch(requestError){error.textContent=requestError.message;error.classList.remove("hidden");}finally{button.disabled=false;button.innerHTML=idle;injectIcons(button);}}
async function loadPortal(){state.data=await api("/api/parent/bootstrap");renderAll();$("#boot-screen").classList.add("hidden");$("#login-screen").classList.add("hidden");$("#parent-shell").classList.remove("hidden");showView(hashView(),false);}
async function logout(){const token=state.token;if(token){try{await fetch("/api/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}});}catch{}}clearSession();history.replaceState(null,"",location.pathname+location.search);showLogin();toast("Signed out securely.");}

function showView(view,updateHash=true){if(!views.has(view))view="overview";state.view=view;$$('.app-view').forEach(node=>node.classList.toggle("active",node.id===view));$$('[data-view]').forEach(node=>{const active=node.dataset.view===view;node.classList.toggle("active",active);active?node.setAttribute("aria-current","page"):node.removeAttribute("aria-current");});const titles={overview:"Overview",attendance:"Attendance",academics:"Academics",fees:"Fees",messages:"Messages",more:"Account"};$("#header-title").textContent=titles[view];if(updateHash&&location.hash!==`#${view}`)history.pushState(null,"",`#${view}`);$("#parent-main").focus({preventScroll:true});window.scrollTo({top:0,behavior:reducedMotion()?"auto":"smooth"});if(view==="messages")loadCommunication();}
function renderAll(){const {profile,assignments,account}=state.data;const accountName=account.fullName;$("#student-context").textContent="Viewing progress for";$("#child-name").textContent=profile.fullName;$("#child-program").textContent=[profile.program,profile.batch].filter(Boolean).join(" · ")||"Academic details pending";$("#child-avatar").textContent=initials(profile.fullName);$("#header-avatar").textContent=initials(accountName);$("#sidebar-avatar").textContent=initials(accountName);$("#sidebar-name").textContent=accountName;$("#sidebar-meta").textContent=account.contactType==="secondary_contact"?"Secondary contact":"Primary contact";["#work-badge","#sidebar-work-badge"].forEach(selector=>{$(selector).textContent=assignments.length;$(selector).classList.toggle("hidden",!assignments.length);});renderOverview();renderAttendance();renderAcademics();renderFees();renderMore();injectIcons();}
function metric(label,value,attention=false){return `<article class="metric-card ${attention?"attention":""}"><span>${esc(label)}</span><strong>${esc(value)}</strong></article>`;}
function renderOverview(){const {summary,schedule,assignments,notices}=state.data;$("#overview-metrics").innerHTML=[metric("Attendance",summary.attendanceRate==null?"Not recorded":`${summary.attendanceRate}%`),metric("Open assignments",String(summary.openAssignments),summary.openAssignments>0),metric("Upcoming exams",String(summary.upcomingExams||0)),metric("Outstanding fees",money(summary.outstandingAmount),summary.outstandingAmount>0)].join("");const next=schedule.find(item=>asInstant(item.startsAt)>=new Date());const pendingAssignments=assignments.filter(item=>item.status!=="completed");$("#next-class").innerHTML=next?`<article class="class-card"><div class="class-time">${timeText(next.startsAt)}</div><div><strong>${esc(next.subject)}</strong><small>${dateLong(next.startsAt)}</small><div class="class-meta"><span class="tag">${esc(next.faculty)}</span><span class="tag">${esc(next.room)}</span></div></div></article>`:empty("calendar","Timetable not published","The next class will appear after the institute publishes the timetable.");$("#pending-work").innerHTML=pendingAssignments.slice(0,3).map(item=>`<div class="compact-row"><span class="row-icon">${icon("book")}</span><span><strong>${esc(item.title)}</strong><small>${esc(item.subject)}</small></span><time>${dateText(item.dueAt)}</time></div>`).join("")||empty("book","Nothing pending","Completed and newly published work will remain available in Academics.");const notice=notices[0];$("#latest-notice").innerHTML=notice?noticeCard(notice):empty("notice","No institute notices","Published announcements will appear here.");}
function renderAttendance(){const rows=state.data.attendance,rate=state.data.summary.attendanceRate,present=rows.filter(item=>["present","late","excused"].includes(item.status)).length,unclassified=rows.filter(item=>item.status==="unclassified").length,classified=rows.length-unclassified;$("#attendance-summary").innerHTML=`<div class="attendance-ring" style="--attendance:${rate||0}%"><div><strong>${rate==null?"—":`${rate}%`}</strong><small>Overall</small></div></div><div class="attendance-copy"><strong>${classified?`${present} of ${classified} classified records attended`:"No classified attendance yet"}</strong><p>${unclassified?`${unclassified} source marks remain unclassified. Only confirmed present and absent marks affect this percentage.`:rows.length?"Attendance includes present, late and excused records.":"Records will appear after attendance is recorded."}</p></div>`;$("#attendance-list").innerHTML=rows.length?rows.map(item=>`<article class="attendance-row"><time>${esc(item.dateLabel||dateText(item.startsAt))}</time><span><strong>${esc(item.subject)}</strong><small>${item.startsAt?timeText(item.startsAt):`Source mark ${esc(item.rawStatus||"—")}`}${item.reason?` · ${esc(item.reason)}`:""}</small></span><em class="status status-${esc(item.status)}">${esc(item.status==="unclassified"&&item.rawStatus?item.rawStatus:item.status)}</em></article>`).join(""):empty("check","Attendance not recorded yet");}
function renderAcademics(){const {schedule,assignments,examinations=[]}=state.data;$("#schedule-list").innerHTML=schedule.length?schedule.map(item=>`<article class="timeline-card"><div class="timeline-time">${dateText(item.startsAt)}<br>${timeText(item.startsAt)}</div><div><h3>${esc(item.subject)}</h3><p>${esc(item.faculty)}</p><footer><span class="tag">${esc(item.room)}</span><span class="tag">${esc(item.subjectCode)}</span></footer></div></article>`).join(""):empty("calendar","Timetable not published","Published classes will appear here.");$("#parent-examination-list").innerHTML=examinations.length?examinations.map(item=>{const published=item.status==="published",graded=published&&item.resultStatus==="graded",result=graded?`${item.marksObtained} / ${item.maxMarks} · ${item.percentage}%`:published?String(item.resultStatus||"Pending").replaceAll("_"," "):asInstant(item.scheduledAt)<new Date()?"Evaluation underway":`${dateText(item.scheduledAt)} · ${timeText(item.scheduledAt)}`;return `<article class="parent-examination-row"><span class="row-icon">${icon("exam")}</span><span><strong>${esc(item.name)}</strong><small>${esc(item.subject)} · ${esc(item.faculty)}</small></span><span><strong>${esc(result)}</strong><small>${graded?(item.qualified?"Qualified":"Below pass mark"):`${item.durationMinutes} min`}</small></span></article>`;}).join(""):empty("exam","No examination records","Schedules and published results will appear here.");$("#assignment-list").innerHTML=assignments.length?assignments.map(item=>`<article class="assignment-card"><header><span class="subject-mark">${esc(item.subject.slice(0,3).toUpperCase())}</span><span class="due-pill">Due ${dateText(item.dueAt)}</span></header><h3>${esc(item.title)}</h3><p>${esc(item.instructions||"Instructions have not been added.")}</p><footer><span>${esc(item.subject)} · ${esc(item.status||"Published")}</span>${item.externalUrl?`<a class="assignment-action" href="${esc(item.externalUrl)}" target="_blank" rel="noopener">Open</a>`:""}</footer></article>`).join(""):empty("book","No assignments published","Faculty has not published any assignments yet.");}
function renderFees(){const fees=state.data.fees,percent=fees.agreedAmount?Math.min(100,Math.round(fees.paidAmount/fees.agreedAmount*100)):0;$("#fee-hero").innerHTML=`<div class="fee-top"><span><span>Outstanding</span><strong>${money(fees.outstandingAmount)}</strong></span><span class="fee-state">${fees.outstandingAmount?"Payment due":"Up to date"}</span></div><div class="fee-progress"><span style="width:${percent}%"></span></div><div class="fee-total"><span>Paid<strong>${money(fees.paidAmount)}</strong></span><span>Agreed fee<strong>${money(fees.agreedAmount)}</strong></span><span>Progress<strong>${percent}%</strong></span></div>`;$("#payment-list").innerHTML=fees.payments.length?fees.payments.map(item=>`<article class="payment-row"><span class="payment-icon">${icon("receipt")}</span><span><strong>${dateText(item.date)}</strong><small>${esc(item.method||"Method not recorded")} · ${esc(item.status)}</small></span><strong>${money(item.amount)}</strong></article>`).join(""):empty("receipt","No payments recorded");}
function noticeCard(item){return `<article class="notice-card"><h3>${esc(item.title)}</h3><p>${esc(item.body)}</p><time>${dateLong(item.publishedAt)}</time></article>`;}
function messageError(selector,error){const node=$(selector);node.textContent=error.message;node.classList.remove("hidden");}
async function loadCommunication(force=false){if(state.communication&&!force){renderCommunication();return;}$("#conversation-list").innerHTML=empty("clock","Loading conversations");try{state.communication=await api("/api/communication/inbox");renderCommunication();}catch(error){$("#conversation-list").innerHTML=empty("notice","Messages unavailable",error.message);}}
function renderCommunication(){const inbox=state.communication||{threads:[],subjects:[]},open=inbox.threads.filter(item=>item.status==="open").length;$("#conversation-count").textContent=`${open} open`;$("#conversation-subject").innerHTML=`<option value="">Institute office</option>${inbox.subjects.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}${item.faculty?.length?` · ${esc(item.faculty.join(", "))}`:""}</option>`).join("")}`;$("#conversation-list").innerHTML=inbox.threads.length?inbox.threads.map(item=>`<button class="message-thread" type="button" data-message-thread="${esc(item.id)}"><span class="row-icon">${icon(item.subjectId?"book":"notice")}</span><span><strong>${esc(item.topic)}</strong><small>${esc(item.subject)} · ${esc(item.lastSender)}</small><p>${esc(item.lastMessage)}</p></span><time>${dateText(item.lastMessageAt)}</time></button>`).join(""):empty("notice","No conversations","Start a conversation with the institute office or assigned subject faculty.");injectIcons($("#messages"));}
async function openMessageThread(threadId){const panel=$("#conversation-detail");panel.classList.remove("hidden");panel.innerHTML=empty("clock","Loading conversation");try{const detail=await api(`/api/communication/threads/${encodeURIComponent(threadId)}`);panel.innerHTML=`<div class="message-detail-head"><div><p class="eyebrow">${esc(detail.subject)}</p><h2>${esc(detail.topic)}</h2><small>${esc(detail.studentName)} · ${esc(detail.status)}</small></div><button class="message-detail-close" type="button" aria-label="Close conversation">×</button></div><div class="message-log">${detail.messages.map(item=>`<article class="message-bubble ${item.senderId===state.identity?.id?"mine":""}"><header><strong>${esc(item.senderName)}</strong><time>${dateText(item.createdAt)} · ${timeText(item.createdAt)}</time></header><p>${esc(item.body)}</p></article>`).join("")}</div>${detail.canReply?`<form class="message-reply-form" id="message-reply-form" data-thread-id="${esc(threadId)}"><label><span>Reply</span><textarea name="body" rows="3" maxlength="3000" required></textarea></label><div class="form-error hidden" id="message-reply-error" role="alert"></div><button class="primary-button" type="submit">Send reply</button></form>`:`<p class="message-closed">This conversation is closed. Start a new conversation if you need further help.</p>`}`;$(".message-detail-close",panel).addEventListener("click",()=>panel.classList.add("hidden"));$("#message-reply-form")?.addEventListener("submit",replyToMessageThread);panel.scrollIntoView({behavior:reducedMotion()?"auto":"smooth",block:"start"});}catch(error){panel.innerHTML=empty("notice","Conversation unavailable",error.message);}}
async function createConversation(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=$("button[type='submit']",form);button.disabled=true;$("#conversation-create-error").classList.add("hidden");try{const detail=await api("/api/communication/threads",{method:"POST",body:JSON.stringify({subjectId:String(data.get("subjectId")||"")||null,topic:String(data.get("topic")||"").trim(),body:String(data.get("body")||"").trim()})});form.reset();form.classList.add("hidden");await loadCommunication(true);await openMessageThread(detail.id);toast("Message sent.");}catch(error){messageError("#conversation-create-error",error);}finally{button.disabled=false;}}
async function replyToMessageThread(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=$("button[type='submit']",form),threadId=form.dataset.threadId;button.disabled=true;$("#message-reply-error").classList.add("hidden");try{await api(`/api/communication/threads/${encodeURIComponent(threadId)}/messages`,{method:"POST",body:JSON.stringify({body:String(data.get("body")||"").trim()})});await loadCommunication(true);await openMessageThread(threadId);}catch(error){messageError("#message-reply-error",error);button.disabled=false;}}
function renderMore(){const {profile,notices,account}=state.data;const contact=account.contactType==="secondary_contact"?"Secondary contact":"Primary contact";const login=account.mobile?`+91 ${account.mobile}`:"Mobile not assigned";$("#account-card").innerHTML=`<span class="profile-avatar">${initials(account.fullName)}</span><span><strong>${esc(account.fullName)}</strong><span>${esc(contact)}</span><span>${esc(login)}</span></span>`;$("#profile-card").innerHTML=`<span class="profile-avatar">${initials(profile.fullName)}</span><span><strong>${esc(profile.fullName)}</strong><span>${esc(profile.admissionNumber)} · ${esc(profile.program||"Program pending")}</span><span>${esc(profile.batch||"Batch pending")}</span></span>`;$("#notice-list").innerHTML=notices.length?notices.map(noticeCard).join(""):empty("notice","No notices published","Institute announcements will appear here.");}
function togglePassword(){const field=$("#login-password"),button=$("#password-toggle"),glyph=$("[data-icon]",button),show=field.type==="password";field.type=show?"text":"password";button.setAttribute("aria-label",show?"Hide password":"Show password");glyph.dataset.icon=show?"eye-off":"eye";injectIcons(button);}
function bindEvents(){$("#login-form").addEventListener("submit",login);$("#password-change-form").addEventListener("submit",changePassword);$("#password-toggle").addEventListener("click",togglePassword);$("#signout-button").addEventListener("click",logout);$("#sidebar-signout").addEventListener("click",logout);$("#profile-button").addEventListener("click",()=>showView("more"));$("#new-conversation").addEventListener("click",()=>$("#conversation-create-form").classList.toggle("hidden"));$("#cancel-conversation").addEventListener("click",()=>$("#conversation-create-form").classList.add("hidden"));$("#conversation-create-form").addEventListener("submit",createConversation);window.addEventListener("popstate",()=>state.data&&showView(hashView(),false));window.addEventListener("online",()=>setConnectionState(true));window.addEventListener("offline",()=>setConnectionState(false));document.addEventListener("click",event=>{const target=event.target.closest("[data-view],[data-go]"),view=target?.dataset.view||target?.dataset.go;if(view){event.preventDefault();showView(view);}const messageThread=event.target.closest("[data-message-thread]");if(messageThread)openMessageThread(messageThread.dataset.messageThread);});}
initialize();
