"""Formatted, typed report downloads generated by the application server."""

from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from io import BytesIO
from math import ceil

from fastapi.responses import Response
from openpyxl import Workbook
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

IST = timezone(timedelta(hours=5, minutes=30))
MONEY_COLUMNS = {"Agreed fee", "Received", "Outstanding", "Balance adjustments", "Credit balance"}


def local_datetime(value):
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(IST).replace(tzinfo=None)


def excel_download(filename, sheets):
    """Each sheet is (name, headings, rows, scope). Exports are dated snapshots."""
    workbook = Workbook()
    workbook.remove(workbook.active)
    workbook.properties.creator = "Lakshya Institute"
    generated = datetime.now(IST).strftime("%d %b %Y, %I:%M %p IST")
    for name, headings, records, scope in sheets:
        rows = list(records)
        sheet = workbook.create_sheet(name)
        sheet.sheet_view.showGridLines = False
        sheet.sheet_properties.pageSetUpPr.fitToPage = True
        sheet.sheet_properties.tabColor = "25265E"
        sheet.cell(2, 1, f"Lakshya Institute — {name}").font = Font(name="Arial", size=15, bold=True, color="25265E")
        sheet.cell(3, 1, f"Generated {generated} · {len(rows)} {'record' if len(rows) == 1 else 'records'}").font = Font(name="Arial", size=10, color="666666")
        # Notes span the report width without widening the first data column.
        sheet.merge_cells(start_row=4, start_column=1, end_row=4, end_column=len(headings))
        sheet.cell(4, 1, scope).alignment = Alignment(wrap_text=True, vertical="center")
        sheet.cell(4, 1).font = Font(name="Arial", size=10, italic=True, color="666666")
        sheet.row_dimensions[4].height = 32
        header_row = 6
        widths = []
        for column, heading in enumerate(headings, 1):
            samples = [len(str(row[column - 1] or "")) for row in rows]
            width = min(48, max(18, len(heading) + 2, min(max(samples, default=0) + 2, 36)))
            if heading in MONEY_COLUMNS:
                width = max(width, 22)
            widths.append(width)
            sheet.column_dimensions[get_column_letter(column)].width = width
            cell = sheet.cell(header_row, column, heading)
            cell.fill = PatternFill("solid", fgColor="25265E")
            cell.font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        sheet.row_dimensions[header_row].height = 32
        for row_number, row in enumerate(rows, header_row + 1):
            lines = 1
            for column, value in enumerate(row, 1):
                if isinstance(value, datetime):
                    value = local_datetime(value)
                if isinstance(value, str):
                    value = ILLEGAL_CHARACTERS_RE.sub("", value)
                cell = sheet.cell(row_number, column, value)
                if isinstance(value, str):
                    # A literal string type preserves phone/ID zeros and prevents formula injection.
                    cell.data_type = "s"
                    cell.number_format = "@"
                elif isinstance(value, datetime):
                    cell.number_format = "dd mmm yyyy hh:mm"
                elif isinstance(value, date):
                    cell.number_format = "dd mmm yyyy"
                elif isinstance(value, (int, float, Decimal)):
                    cell.number_format = '"₹" #,##0;[Red]("₹" #,##0);"₹" 0' if headings[column - 1] in MONEY_COLUMNS else "0.0%" if headings[column - 1] == "Attendance rate" else "#,##0"
                cell.font = Font(name="Arial", size=11, color="20212B")
                cell.alignment = Alignment(vertical="top", wrap_text=True, indent=1, horizontal="right" if isinstance(value, (int, float, Decimal)) else "left")
                if row_number % 2:
                    cell.fill = PatternFill("solid", fgColor="F3F4FA")
                lines = max(lines, sum(max(1, ceil(len(part) / max(1, widths[column - 1] - 2))) for part in str(value or "").split("\n")))
            sheet.row_dimensions[row_number].height = min(409, max(26, lines * 16 + 8))
        last_row = header_row + len(rows)
        last_column = get_column_letter(len(headings))
        sheet.freeze_panes = "C7"
        sheet.auto_filter.ref = f"A6:{last_column}{max(6, last_row)}"
        if not rows:
            sheet.cell(7, 1, "No records found.").font = Font(name="Arial", size=11, color="666666")
            last_row = 7
        if rows and any(heading in MONEY_COLUMNS for heading in headings):
            last_row += 2
            sheet.cell(last_row, 1, "Total (snapshot)")
            for column, heading in enumerate(headings, 1):
                cell = sheet.cell(last_row, column)
                if heading in MONEY_COLUMNS:
                    cell.value = sum(row[column - 1] or 0 for row in rows)
                    cell.number_format = '"₹" #,##0;[Red]("₹" #,##0);"₹" 0'
                cell.font = Font(name="Arial", size=11, bold=True, color="25265E")
                cell.border = Border(top=Side(style="thin", color="25265E"))
            sheet.row_dimensions[last_row].height = 28
        sheet.print_title_rows = "1:6"
        sheet.print_options.horizontalCentered = True
        sheet.print_area = f"A1:{last_column}{last_row}"
        sheet.page_setup.orientation = "landscape"
        sheet.page_setup.paperSize = sheet.PAPERSIZE_A3 if len(headings) > 8 else sheet.PAPERSIZE_A4
        sheet.page_setup.fitToWidth = 1
        sheet.page_setup.fitToHeight = 0
        sheet.oddFooter.center.text = "Page &P of &N"
    output = BytesIO()
    workbook.save(output)
    return Response(output.getvalue(), media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", headers={
        "Content-Disposition": f'attachment; filename="{filename}"',
        "Cache-Control": "no-store",
        "X-Content-Type-Options": "nosniff",
    })
