"""legacy admissions import ledger"""
from alembic import op
import sqlalchemy as sa

revision = 'b4aeed152956'
down_revision = 'd6c70c2e7aaf'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_rows', sa.Integer(), nullable=False),
    sa.Column('cancelled_rows', sa.Integer(), nullable=False),
    sa.Column('fee_total', sa.Integer(), nullable=False),
    sa.Column('registration_total', sa.Integer(), nullable=False),
    sa.Column('staged_payment_total', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_source_hash'), 'import_batches', ['source_hash'], unique=True)
    op.create_table('fee_agreements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('enrollment_id', sa.String(length=64), nullable=False),
    sa.Column('legacy_import_id', sa.String(length=80), nullable=False),
    sa.Column('agreed_amount', sa.Integer(), nullable=False),
    sa.Column('legacy_registration_total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_fee_agreements_legacy_import_id'), 'fee_agreements', ['legacy_import_id'], unique=True)
    op.create_index(op.f('ix_fee_agreements_student_id'), 'fee_agreements', ['student_id'], unique=False)
    op.create_table('legacy_admission_rows',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('import_batch_id', sa.String(length=64), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=24), nullable=False),
    sa.Column('import_readiness', sa.String(length=24), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_legacy_admission_rows_import_batch_id'), 'legacy_admission_rows', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_legacy_admission_rows_import_readiness'), 'legacy_admission_rows', ['import_readiness'], unique=False)
    op.create_index(op.f('ix_legacy_admission_rows_record_status'), 'legacy_admission_rows', ['record_status'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('fee_agreement_id', sa.String(length=64), nullable=False),
    sa.Column('legacy_import_id', sa.String(length=80), nullable=False),
    sa.Column('legacy_line_number', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reconciliation_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fee_agreement_id'], ['fee_agreements.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_import_id', 'legacy_line_number', name='uq_legacy_payment_line')
    )
    op.create_index(op.f('ix_payment_transactions_fee_agreement_id'), 'payment_transactions', ['fee_agreement_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_legacy_import_id'), 'payment_transactions', ['legacy_import_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_reconciliation_status'), 'payment_transactions', ['reconciliation_status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_student_id'), 'payment_transactions', ['student_id'], unique=False)
    op.add_column('enrollments', sa.Column('enrollment_date', sa.Date(), nullable=True))
    op.add_column('enrollments', sa.Column('source_type', sa.String(length=32), nullable=False, server_default='erp'))
    op.add_column('enrollments', sa.Column('legacy_import_id', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_enrollments_legacy_import_id'), 'enrollments', ['legacy_import_id'], unique=True)
    op.add_column('students', sa.Column('secondary_mobile', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('previous_school', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('legacy_import_id', sa.String(length=80), nullable=True))
    op.add_column('students', sa.Column('data_quality_status', sa.String(length=24), nullable=False, server_default='ready'))
    with op.batch_alter_table('students') as batch_op:
        batch_op.alter_column('mobile', existing_type=sa.VARCHAR(length=20), nullable=True)
    op.create_index(op.f('ix_students_data_quality_status'), 'students', ['data_quality_status'], unique=False)
    op.create_index(op.f('ix_students_legacy_import_id'), 'students', ['legacy_import_id'], unique=True)
    op.create_index(op.f('ix_students_secondary_mobile'), 'students', ['secondary_mobile'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_secondary_mobile'), table_name='students')
    op.drop_index(op.f('ix_students_legacy_import_id'), table_name='students')
    op.drop_index(op.f('ix_students_data_quality_status'), table_name='students')
    with op.batch_alter_table('students') as batch_op:
        batch_op.alter_column('mobile', existing_type=sa.VARCHAR(length=20), nullable=False)
    op.drop_column('students', 'data_quality_status')
    op.drop_column('students', 'legacy_import_id')
    op.drop_column('students', 'previous_school')
    op.drop_column('students', 'secondary_mobile')
    op.drop_index(op.f('ix_enrollments_legacy_import_id'), table_name='enrollments')
    op.drop_column('enrollments', 'legacy_import_id')
    op.drop_column('enrollments', 'source_type')
    op.drop_column('enrollments', 'enrollment_date')
    op.drop_index(op.f('ix_payment_transactions_student_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_reconciliation_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_legacy_import_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_fee_agreement_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_legacy_admission_rows_record_status'), table_name='legacy_admission_rows')
    op.drop_index(op.f('ix_legacy_admission_rows_import_readiness'), table_name='legacy_admission_rows')
    op.drop_index(op.f('ix_legacy_admission_rows_import_batch_id'), table_name='legacy_admission_rows')
    op.drop_table('legacy_admission_rows')
    op.drop_index(op.f('ix_fee_agreements_student_id'), table_name='fee_agreements')
    op.drop_index(op.f('ix_fee_agreements_legacy_import_id'), table_name='fee_agreements')
    op.drop_table('fee_agreements')
    op.drop_index(op.f('ix_import_batches_source_hash'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
