"use strict";

const icons = {
  arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>', home:'<path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1v-9Z"/>', calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/>', book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5v13Z"/><path d="M4 19.5A2.5 2.5 0 0 0 6.5 22H20v-5"/>', check:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="m8 14 2.5 2.5L16 11"/>', more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>', spark:'<path d="m12 3 1.4 4.1 4.1 1.4-4.1 1.4L12 14l-1.4-4.1-4.1-1.4 4.1-1.4L12 3Z"/>', clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', notice:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>', logout:'<path d="m10 17 5-5-5-5m5 5H3m12-9h5a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-5"/>', wallet:'<path d="M4 5h15a2 2 0 0 1 2 2v12H4a2 2 0 0 1-2-2V5.5A2.5 2.5 0 0 1 4.5 3H18"/>', eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>', 'eye-off':'<path d="m3 3 18 18M10.6 5.2A11.4 11.4 0 0 1 12 5c6.5 0 10 7 10 7a16 16 0 0 1-2.1 3.2M6.6 6.6C3.6 8.6 2 12 2 12s3.5 7 10 7a10.7 10.7 0 0 0 4.1-.8M9.9 9.9a3 3 0 0 0 4.2 4.2"/>'
};
const views = new Set(["home","schedule","assignments","attendance","more"]);
const hashView = () => views.has(location.hash.slice(1)) ? location.hash.slice(1) : "home";
const state = { token: localStorage.getItem("lakshya_student_token"), data: null, view: hashView(), assignmentFilter: "open", scheduleDate: null };
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.spark}</svg>`;
const esc = (value="") => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const initials = name => String(name || "LS").split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();
const money = value => new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value||0));
const dateKey = value => new Date(value).toISOString().slice(0,10);
const dateText = value => new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short"}).format(new Date(value));
const dateLong = value => new Intl.DateTimeFormat("en-IN",{weekday:"short",day:"numeric",month:"short"}).format(new Date(value));
const timeText = value => new Intl.DateTimeFormat("en-IN",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));

function injectIcons(root=document){ $$('[data-icon]',root).forEach(node=>{node.innerHTML=icon(node.dataset.icon);}); }
async function api(path, options={}) {
  const headers={"Content-Type":"application/json",...(options.headers||{})}; if(state.token) headers.Authorization=`Bearer ${state.token}`;
  const response=await fetch(path,{cache:"no-store",...options,headers}); let body={}; try{body=await response.json();}catch{}
  if(response.status===401){ clearSession(); showLogin("Your session expired. Sign in again."); }
  if(!response.ok){ const detail=body?.detail; throw new Error(typeof detail==="string"?detail:detail?.message||body?.error?.message||"Unable to complete this request."); }
  return body;
}
function clearSession(){ state.token=null; state.data=null; localStorage.removeItem("lakshya_student_token"); }
function showLogin(message=""){ $("#boot-screen").classList.add("hidden"); $("#student-shell").classList.add("hidden"); $("#login-screen").classList.remove("hidden"); $("#login-password").value=""; if(message){$("#login-error").textContent=message;$("#login-error").classList.remove("hidden");} else {$("#login-error").classList.add("hidden");} requestAnimationFrame(()=>$("#login-email").focus()); }
function toast(message){ const node=document.createElement("div");node.className="toast";node.textContent=message;$("#toast-region").append(node);setTimeout(()=>node.remove(),2800); }

async function initialize(){ injectIcons(); bindEvents(); if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{}); if(!state.token){showLogin();return;} try{await loadPortal();}catch(error){clearSession();showLogin(error.message);} }
async function login(event){ event.preventDefault(); const button=$("#login-button"),idle=button.innerHTML; button.disabled=true;button.textContent="Signing in…"; $("#login-error").classList.add("hidden"); try{ const form=new FormData(event.currentTarget); const result=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:String(form.get("email")).trim(),password:String(form.get("password"))})}); state.token=result.access_token; const account=await api("/api/auth/me"); if(!["student","parent_student"].includes(account.role))throw new Error("This login is not assigned to the Student portal."); localStorage.setItem("lakshya_student_token",state.token); await loadPortal(); }catch(error){clearSession();showLogin(error.message);}finally{button.disabled=false;button.innerHTML=idle;injectIcons(button);} }
async function loadPortal(){ state.data=await api("/api/portal/bootstrap"); renderAll(); $("#boot-screen").classList.add("hidden");$("#login-screen").classList.add("hidden");$("#student-shell").classList.remove("hidden");showView(hashView(),false); }
async function logout(){ const token=state.token; if(token){try{await fetch("/api/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}});}catch{}} clearSession();history.replaceState(null,"",location.pathname+location.search);showLogin();toast("Signed out securely."); }

function showView(view,updateHash=true){ if(!views.has(view))view="home"; state.view=view; $$(".portal-view").forEach(node=>node.classList.toggle("active",node.id===view)); $$("[data-view]").forEach(node=>{const active=node.dataset.view===view;node.classList.toggle("active",active);active?node.setAttribute("aria-current","page"):node.removeAttribute("aria-current");}); const titles={home:"Home",schedule:"Schedule",assignments:"Assignments",attendance:"Attendance",more:"Account"};$("#header-title").textContent=titles[view];if(updateHash&&location.hash!==`#${view}`)history.pushState(null,"",`#${view}`);$("#student-main").focus({preventScroll:true});window.scrollTo({top:0,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}); }
function renderAll(){ const {profile}=state.data; const meta=[profile.admissionNumber,profile.program].filter(Boolean).join(" · "); $("#today-label").textContent=new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long"}).format(new Date()).toUpperCase(); $("#student-first-name").textContent=profile.fullName.split(/\s+/)[0]; $("#student-program").textContent=[profile.program,profile.batch].filter(Boolean).join(" · ")||"Academic details pending"; $("#header-avatar").textContent=initials(profile.fullName);$("#sidebar-avatar").textContent=initials(profile.fullName);$("#sidebar-name").textContent=profile.fullName;$("#sidebar-meta").textContent=meta||"Student account"; renderHome();renderSchedule();renderAssignments();renderAttendance();renderMore();injectIcons(); }
function empty(name,title,copy=""){return `<div class="empty"><div><span>${icon(name)}</span><strong>${esc(title)}</strong>${copy?`<p>${esc(copy)}</p>`:""}</div></div>`;}
function summaryCard(label,value,featured=false){return `<article class="summary-card ${featured?"featured":""}"><span>${esc(label)}</span><strong>${esc(value)}</strong></article>`;}
function classCard(item){return `<article class="class-card"><div class="class-time">${timeText(item.startsAt)}</div><div><strong>${esc(item.subject)}</strong><small>${dateLong(item.startsAt)}</small><div class="class-meta"><span>${esc(item.faculty)}</span><span>${esc(item.room)}</span></div></div></article>`;}
function renderHome(){ const {summary,schedule,assignments,notices}=state.data; $("#summary-strip").innerHTML=[summaryCard("Upcoming classes",String(summary.upcomingClasses)),summaryCard("Open assignments",String(summary.openAssignments),summary.openAssignments>0),summaryCard("Attendance",summary.attendanceRate==null?"Not recorded":`${summary.attendanceRate}%`),summaryCard("Outstanding fees",money(summary.outstandingAmount))].join(""); const next=schedule.find(item=>new Date(item.startsAt)>=new Date()); $("#next-class").innerHTML=next?classCard(next):empty("calendar","Timetable not published","Your next class will appear when the institute publishes the timetable."); $("#home-assignments").innerHTML=assignments.slice(0,3).map(item=>`<div class="compact-row"><span class="compact-icon">${icon("book")}</span><span><strong>${esc(item.title)}</strong><small>${esc(item.subject)}</small></span><time>${dateText(item.dueAt)}</time></div>`).join("")||empty("book","No published assignments","New work will appear here after it is published by faculty."); const notice=notices[0];$("#latest-notice").innerHTML=notice?`<article class="notice-preview"><strong>${esc(notice.title)}</strong><span>${esc(notice.body)}</span></article>`:empty("notice","No institute notices","Published announcements will appear here."); }
function renderSchedule(){ const rows=state.data.schedule; const dates=[...new Set(rows.map(item=>dateKey(item.startsAt)))]; if(!state.scheduleDate||!dates.includes(state.scheduleDate)){state.scheduleDate=dates.find(key=>key>=dateKey(new Date()))||dates[0]||null;} $("#schedule-dates").innerHTML=dates.map(key=>`<button type="button" class="${key===state.scheduleDate?"active":""}" data-schedule-date="${key}" aria-pressed="${key===state.scheduleDate}">${dateLong(`${key}T12:00:00`)}</button>`).join(""); const visible=rows.filter(item=>!state.scheduleDate||dateKey(item.startsAt)===state.scheduleDate); $("#schedule-list").innerHTML=visible.length?visible.map(item=>`<article class="timeline-card"><div class="timeline-time">${timeText(item.startsAt)}<br>${timeText(item.endsAt)}</div><div><h3>${esc(item.subject)}</h3><p>${esc(item.faculty)}</p><footer><span class="tag">${esc(item.room)}</span><span class="tag">${esc(item.subjectCode)}</span></footer></div></article>`).join(""):empty("calendar",rows.length?"No classes on this day":"Schedule not published"); }
function renderAssignments(){ const now=Date.now(),all=state.data.assignments,rows=state.assignmentFilter==="open"?all.filter(item=>new Date(item.dueAt).getTime()>=now):all; const open=all.filter(item=>new Date(item.dueAt).getTime()>=now).length;["#assignment-badge","#sidebar-assignment-badge"].forEach(selector=>{$(selector).textContent=open;$(selector).classList.toggle("hidden",!open);}); $("#assignment-list").innerHTML=rows.length?rows.map(item=>`<article class="assignment-card"><header><span class="subject-mark">${esc(item.subject.slice(0,3).toUpperCase())}</span><span class="due-pill">Due ${dateText(item.dueAt)}</span></header><h3>${esc(item.title)}</h3><p>${esc(item.instructions||"Instructions have not been added.")}</p><footer><span>${esc(item.subject)} · ${esc(item.batch)}</span>${item.externalUrl?`<a href="${esc(item.externalUrl)}" target="_blank" rel="noopener">Open</a>`:""}</footer></article>`).join(""):empty("book",state.assignmentFilter==="open"?"No open assignments":"No assignments published",state.assignmentFilter==="open"?"Published work that is still due will appear here.":"Faculty has not published any assignments yet."); }
function renderAttendance(){ const rows=state.data.attendance,rate=state.data.summary.attendanceRate;$("#attendance-hero").innerHTML=`<div class="attendance-ring" style="--attendance:${rate==null?0:rate}%"><div><strong>${rate==null?"—":`${rate}%`}</strong><small>Overall</small></div></div>`; $("#attendance-list").innerHTML=rows.length?rows.map(item=>`<article class="attendance-row"><time>${dateText(item.startsAt)}</time><span><strong>${esc(item.subject)}</strong><small>${timeText(item.startsAt)}</small></span><em class="status status-${esc(item.status)}">${esc(item.status)}</em></article>`).join(""):empty("check","Attendance not recorded yet","Records will appear after faculty submits attendance."); }
function renderMore(){ const {profile,fees,notices}=state.data;$("#profile-card").innerHTML=`<span class="profile-avatar">${initials(profile.fullName)}</span><span><strong>${esc(profile.fullName)}</strong><span>${esc(profile.admissionNumber)} · ${esc(profile.program||"Program pending")}</span><span>${esc(profile.batch||"Batch pending")}</span></span>`; const percent=fees.agreedAmount?Math.min(100,Math.round(fees.paidAmount/fees.agreedAmount*100)):0;$("#fee-summary").innerHTML=`<div class="fee-total"><span><span>Outstanding</span><strong>${money(fees.outstandingAmount)}</strong></span><span><span>Agreed fee</span><strong>${money(fees.agreedAmount)}</strong></span></div><div class="fee-progress"><span style="width:${percent}%"></span></div><div class="fee-caption"><span>${money(fees.paidAmount)} paid</span><span>${percent}%</span></div>`; $("#notice-list").innerHTML=notices.length?notices.map(item=>`<article class="notice-card"><h3>${esc(item.title)}</h3><p>${esc(item.body)}</p><time>${dateLong(item.publishedAt)}</time></article>`).join(""):empty("notice","No notices"); }

function togglePassword(){const field=$("#login-password"),button=$("#password-toggle"),glyph=$("[data-icon]",button),show=field.type==="password";field.type=show?"text":"password";button.setAttribute("aria-label",show?"Hide password":"Show password");glyph.dataset.icon=show?"eye-off":"eye";injectIcons(button);}
function bindEvents(){ $("#login-form").addEventListener("submit",login);$("#password-toggle").addEventListener("click",togglePassword);$("#signout-button").addEventListener("click",logout);$("#sidebar-signout").addEventListener("click",logout);$("#profile-button").addEventListener("click",()=>showView("more"));window.addEventListener("popstate",()=>state.data&&showView(hashView(),false));document.addEventListener("click",event=>{const target=event.target.closest("[data-view],[data-go]");const view=target?.dataset.view||target?.dataset.go;if(view){event.preventDefault();showView(view);}const date=event.target.closest("[data-schedule-date]")?.dataset.scheduleDate;if(date){state.scheduleDate=date;renderSchedule();}const filter=event.target.closest("[data-assignment-filter]")?.dataset.assignmentFilter;if(filter){state.assignmentFilter=filter;$$('[data-assignment-filter]').forEach(node=>{const active=node.dataset.assignmentFilter===filter;node.classList.toggle("active",active);node.setAttribute("aria-pressed",String(active));});renderAssignments();}}); }

initialize();
